import assignment4.FileUtils;
import assignment4.Grammar;
import assignment4.SentenceGenerator;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.HashMap;
/**
 * Client handler class that helps server to handle connected client
 */
public class ClientHandler implements Runnable {
  final private int ZERO = 0;
  final private int ONE = 1;
  final private String THERE_ARE = "There are ";
  final private String OTHER_CONNECTED_CLIENTS = " other connected clients.";
  final private String DISCONNECTED_SUCCESS_MESSAGE = "You are no longer connected.";
  final private String TO_ALL =  " -> all: ";
  final private String TO = " -> ";
  final private String COLON = ": ";
  final private String GRAMMAR_PATH = "./testFiles/grammars/insult_grammar.json";
  final private String IS_INVALID_USERNAME = " is a invalid username";
  public static HashMap<String, ClientHandler> clientHandlers = new HashMap<>();
  private Socket socket;
  private DataInputStream dataReader;
  private DataOutputStream dataWriter;
  private String clientUsername;

  /**
   * Constructs client handler instance
   * @param socket New socket generated by the server after accepting a new client
   */
  public ClientHandler(Socket socket) {
    try {
      this.socket = socket;
      this.dataReader = new DataInputStream(socket.getInputStream());
      this.dataWriter = new DataOutputStream(socket.getOutputStream());
    } catch (IOException e) {
      removeClientHandler();
    }
  }

  /**
   * Listen to the message from the corresponding client
   */
  @Override
  public void run() {
    while (socket.isConnected()) {
      try {
        int messageIdentifier = dataReader.readInt();
        dataReader.readChar();
        switch (messageIdentifier) {
          case Constants.CONNECT_MESSAGE:
            handleConnectMessage();
            break;
          case Constants.DISCONNECT_MESSAGE:
            handleDisconnectMessage();
            break;
          case Constants.QUERY_CONNECTED_USERS:
            handleQueryConnectedUsers();
            break;
          case Constants.BROADCAST_MESSAGE:
            handleBroadcastMessage();
            break;
          case Constants.DIRECT_MESSAGE:
            handleDirectMessage();
            break;
          case Constants.SEND_INSULT:
            handleInsultMessage();
            break;
        }
      } catch (IOException e) {
        removeClientHandler();
        break;
      }
    }
  }

  /**
   * Handles connect message
   * @throws IOException I/O exception
   */
  public void handleConnectMessage() throws IOException {
    try {
      int usernameLength = dataReader.readInt();
      dataReader.readChar();
      clientUsername = dataReader.readUTF();
      clientHandlers.put(clientUsername, this);

      dataWriter.writeInt(Constants.CONNECT_RESPONSE);
      dataWriter.writeChar(Constants.SPACE);
      dataWriter.writeBoolean(true);
      dataWriter.writeChar(Constants.SPACE);
      String response = THERE_ARE + (clientHandlers.size() - ONE) + OTHER_CONNECTED_CLIENTS;
      dataWriter.writeInt(response.length());
      dataWriter.writeChar(Constants.SPACE);
      dataWriter.writeUTF(response);
    } catch (IOException e) {
      dataWriter.writeInt(Constants.CONNECT_RESPONSE);
      dataWriter.writeChar(Constants.SPACE);
      dataWriter.writeBoolean(false);
      dataWriter.writeChar(Constants.SPACE);
      String response = e.toString();
      dataWriter.writeInt(response.length());
      dataWriter.writeChar(Constants.SPACE);
      dataWriter.writeUTF(response);
      removeClientHandler();
    }
  }

  /**
   * Handles disconnect message
   * @throws IOException I/O exception
   */
  public void handleDisconnectMessage() throws IOException {
    try {
      int usernameLength = dataReader.readInt();
      dataReader.readChar();
      clientUsername = dataReader.readUTF();
      clientHandlers.remove(clientUsername);

      dataWriter.writeInt(Constants.CONNECT_RESPONSE);
      dataWriter.writeChar(Constants.SPACE);
      dataWriter.writeBoolean(true);
      dataWriter.writeChar(Constants.SPACE);
      dataWriter.writeInt(DISCONNECTED_SUCCESS_MESSAGE.length());
      dataWriter.writeChar(Constants.SPACE);
      dataWriter.writeUTF(DISCONNECTED_SUCCESS_MESSAGE);

      removeClientHandler();
    } catch (IOException e) {
      dataWriter.writeInt(Constants.CONNECT_RESPONSE);
      dataWriter.writeChar(Constants.SPACE);
      dataWriter.writeBoolean(false);
      dataWriter.writeChar(Constants.SPACE);
      String response = e.toString();
      dataWriter.writeInt(response.length());
      dataWriter.writeChar(Constants.SPACE);
      dataWriter.writeUTF(response);
    }
  }

  /**
   * Handles query connected users message
   * @throws IOException I/O exception
   */
  public void handleQueryConnectedUsers() throws IOException {
    try {
      int usernameLength = dataReader.readInt();
      dataReader.readChar();
      String senderUsername = dataReader.readUTF();

      dataWriter.writeInt(Constants.QUERY_USER_RESPONSE);
      dataWriter.writeChar(Constants.SPACE);
      dataWriter.writeInt(clientHandlers.size() - ONE); // number of other users

      for (String username : clientHandlers.keySet()) {
        if (!username.equals(senderUsername)) {
          dataWriter.writeChar(Constants.SPACE);
          dataWriter.writeInt(username.length());
          dataWriter.writeChar(Constants.SPACE);
          dataWriter.writeUTF(username);
        }
      }
    } catch (IOException e) {
      dataWriter.writeInt(Constants.QUERY_USER_RESPONSE);
      dataWriter.writeChar(Constants.SPACE);
      dataWriter.writeInt(ZERO);
    }
  }

  /**
   * Handles broadcast message
   * @throws IOException I/O exception
   */
  public void handleBroadcastMessage() throws IOException {
    int usernameLength = dataReader.readInt();
    dataReader.readChar();
    String senderUsername = dataReader.readUTF();

    if (clientHandlers.containsKey(senderUsername)) {
      dataReader.readChar();
      int messageLength = dataReader.readInt();
      dataReader.readChar();
      String message = senderUsername + TO_ALL + dataReader.readUTF();

      for (ClientHandler clientHandler : clientHandlers.values()) {
        clientHandler.dataWriter.writeInt(Constants.BROADCAST_MESSAGE);
        clientHandler.dataWriter.writeChar(Constants.SPACE);
        clientHandler.dataWriter.writeInt(message.length());
        clientHandler.dataWriter.writeChar(Constants.SPACE);
        clientHandler.dataWriter.writeUTF(message);
      }
    } else {
      responseFailedMessage(senderUsername);
    }
  }

  /**
   * Handles direct message
   * @throws IOException I/O exception
   */
  public void handleDirectMessage() throws IOException {
    int senderUsernameLength = dataReader.readInt();
    dataReader.readChar();
    String senderUsername = dataReader.readUTF();
    dataReader.readChar();
    int recipientUsernameLength = dataReader.readInt();
    dataReader.readChar();
    String recipientUsername = dataReader.readUTF();
    dataReader.readChar();
    int messageLength = dataReader.readInt();
    dataReader.readChar();
    String message = senderUsername + TO + recipientUsername + COLON + dataReader.readUTF();

    if (!clientHandlers.containsKey(senderUsername)) {
      responseFailedMessage(senderUsername);
    } else if (!clientHandlers.containsKey(recipientUsername)) {
      responseFailedMessage(recipientUsername);
    } else {
      ClientHandler recipientClientHandler = clientHandlers.get(recipientUsername);
      recipientClientHandler.dataWriter.writeInt(Constants.DIRECT_MESSAGE);
      recipientClientHandler.dataWriter.writeChar(Constants.SPACE);
      recipientClientHandler.dataWriter.writeInt(message.length());
      recipientClientHandler.dataWriter.writeChar(Constants.SPACE);
      recipientClientHandler.dataWriter.writeUTF(message);
    }
  }

  /**
   * Handles insult message
   * @throws IOException I/O exception
   */
  public void handleInsultMessage() throws IOException {
    FileUtils fileUtils = new FileUtils();
    Grammar grammar = fileUtils.readGrammar(GRAMMAR_PATH);
    SentenceGenerator sentenceGenerator = new SentenceGenerator();
    String insult = sentenceGenerator.generateSentences(grammar);

    int senderUsernameLength = dataReader.readInt();
    dataReader.readChar();
    String senderUsername = dataReader.readUTF();
    dataReader.readChar();
    int recipientUsernameLength = dataReader.readInt();
    dataReader.readChar();

    String recipientUsername = dataReader.readUTF();
    String insultMessage = senderUsername + TO + recipientUsername + COLON + insult;

    if (!clientHandlers.containsKey(senderUsername)) {
      responseFailedMessage(senderUsername);
    } else if (!clientHandlers.containsKey(recipientUsername)) {
      responseFailedMessage(recipientUsername);
    } else {
      for (ClientHandler clientHandler : clientHandlers.values()) {
        clientHandler.dataWriter.writeInt(Constants.SEND_INSULT);
        clientHandler.dataWriter.writeChar(Constants.SPACE);
        clientHandler.dataWriter.writeInt(insultMessage.length());
        clientHandler.dataWriter.writeChar(Constants.SPACE);
        clientHandler.dataWriter.writeUTF(insultMessage);
      }
    }
  }

  /**
   * Responses failed message
   * @param username invalid username
   * @throws IOException I/O exception
   */
  public void responseFailedMessage(String username) throws IOException {
    dataWriter.writeInt(Constants.FAILED_MESSAGE);
    dataWriter.writeChar(Constants.SPACE);
    String failedMessage = username + IS_INVALID_USERNAME;
    dataWriter.writeInt(failedMessage.length());
    dataWriter.writeChar(Constants.SPACE);
    dataWriter.writeUTF(failedMessage);
  }

  /**
   * Removes client handler
   */
  public void removeClientHandler() {
    clientHandlers.remove(this);
    Client.closeSocketAndStream(socket, dataReader, dataWriter);
  }
}
